Dni jne json
giansalex/peru-consult pull request #23
Opened 2019-10-17 07:01 UTC by brianpando

Codigo para consultar mediante JNE JSON mediante CURL.

2019-10-17 15:30 UTC, giansalex commented
Hola @brianpando, gracias! por la contribución, veo que varias cosas del CI se han caido por que estoy usando un HTTP Server Mock, agregare este nuevo payload.
 Acerca del uso de curl, se podria seguir usando el httpclient que se ha venido usando, creo que podría funcionar de esta forma.
```php
$json = $this->client->post($url, json_encode(['CODDNI' => $dni], [
 'Content-Type' => 'application/json;chartset=utf-8',
 'Requestverificationtoken' => '30OB7qfO2MmL2Kcr1z4S0ttQcQpxH9pDUlZnkJPVgUhZOGBuSbGU4qM83JcSu7DZpZw-IIIfaDZgZ4vDbwE5-L9EPoBIHOOC1aSPi4FS_Sc1:clDOiaq7mKcLTK9YBVGt2R3spEU8LhtXEe_n5VG5VLPfG9UkAQfjL_WT9ZDmCCqtJypoTD26ikncynlMn8fPz_F_Y88WFufli38cUM-24PE1',
]));
$raw = json_decode($json)->data;
```

2019-10-17 21:53 UTC, giansalex requested changes
Utilizar HTTP Client implementado.

2019-10-17 22:19 UTC, brianpando commented
buen punto!

2019-10-18 22:33 UTC, brianpando commented
Hola, cambie el codigo para usarlo de la forma que comentas, funciona bien, pero no se como resolver para el async phpreact. ¿Como pasas el parametro de DNI via POST con esa libreria?

2019-10-19 03:27 UTC, giansalex approved these changes
Gracias @brianpando, agregue la parte que faltaba

2019-10-19 03:28 UTC, merged